sky:
  datasource:
    driver-class-name:
    host:
    port:
    database:
    username:
    password:
  redis:
    host:
    port:
    password:
    database:
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  wechat:
    appid:
    secret:
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiv3key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
  shop:
    address:
  baidu:
    ak:
